### ISSUE TITLE
Notifications displayed as [Invalid UTF-8]

### ISSUE THREAD

**Issue by codyfish** [sonnyp/Tangram#38] opened 2019-08-21 10:25 UTC
Notifications from WhatsApp are shown as [Invalid UTF-8], no matter if they contain special characters or emojis or not.

This issue has been existing for a while now and might be related to [Custom Applications Notifications](https://github.com/sonnyp/Tangram/issues/21). So far I haven't had time to dig into this and will not have any time for the next week. It exists as well when not using custom applications. I do not know if the issue exists for other applications.

**Comment by sonnyp** [comment] 2019-08-25 12:20
Flatpak?

Weird. I can't even seem to get desktop notifications for WhatsApp now, no idea why. I'll have a look.

**Comment by sonnyp** [comment] 2019-08-27 12:46
Might be fixed with https://github.com/sonnyp/Tangram/commit/fda32f0d1bac311a136dc3cc82849b72ed29c4af#diff-0c764a4939f5d31ce3d5b87f48df10db

Please try master. Also what is your gjs version and desktop environment?

**Comment by codyfish** [comment] 2019-08-28 12:25
It seems to work when not focusing the window. Do you have to minimize it in order to show notifications?

gjs-version:
2:1.56.2-1

I use i3-gaps on arch. Notifications are handled by libnotify  0.7.8-1 and dunst 1.4.1-1.

**Comment by sonnyp** [comment] 2019-08-28 13:07
> It seems to work when not focusing the window. Do you have to minimize it in order to show notifications?

Not here on my setup (GNOME Shell), most likely related to your setup. If you find a solution please share.

**Comment by codyfish** [comment] 2019-08-28 14:22
Yes I'll do that.

**Comment by codyfish** [comment] 2019-08-28 15:38
It seems the issue comes directly from `WebKit2`s WebView.

`["show-notification"](notification) {
        onNotification(notification, instance.id);
        return true;
      },`

If I understood correctly, `onNotification` is called when `WebView` fires a event. I logged to calls of `onNotification`, and they also do not always pop up (when not in focus, which seems difficult to determine after changing workspace).

**Comment by sonnyp** [comment] 2019-08-28 16:16
Oh my bad then. Weird. WhatsApp?

`when not in focus` you mean when Tangram is not the active application or when the tab is not selected or when the WebView widget does not have focus or something else?

**Comment by sonnyp** [comment] 2019-08-28 17:06
Okay I can reproduce with WhatsApp:

1. Load WhatsApp
2. Receive a message somehow

Result: The desktop notification does not show unless you switch to an other application.

It does not happen on Epiphany/Firefox.

**Comment by sonnyp** [comment] 2019-08-28 18:41
Can you try the branch `fix-notifications` ?

**Comment by codyfish** [comment] 2019-08-29 10:13
It still doesn't displays notifications when having focused the window (which isn't a problem, more like an actual feature), but I got every other notification, also when not unfocusing it (by clicking on another window) and only switching workspace, so it's definitely an improvement.

**Comment by sonnyp** [comment] 2019-08-29 11:32
Okay I'll close this then because it's unrelated to the initial issue and we can create a new issue if it becomes a problem.

**Closed by sonnyp** 2019-08-29 11:32 UTC

**Comment by codyfish** [comment] 2019-08-31 07:43
Yeah, that makes sense. For me, it's not a problem at the moment.
