### ISSUE TITLE
Main Window is a few pixels too wide on smartphones (Librem 5, PinePhone, ...)

### ISSUE THREAD

**Issue by 1peter10** [sonnyp/Tangram#233] opened 2023-02-11 10:10 UTC
Hi Sonny, 

great work on making the app adaptive - the GTK4/libadwaita release is really a pleasure to use!

Sadly, trying the current release from Flathub, it's just a few pixels too wide:
![tangram-too-wide-1](https://user-images.githubusercontent.com/32742559/218252128-78e8dec0-7906-4ef8-9b88-3023b216aba5.png)
![tangram-too-wide-2](https://user-images.githubusercontent.com/32742559/218252125-f6b5ace9-a40e-4bf8-b3a5-80ae111432bb.png)

The screenshots were made today on a OnePlus 6 running postmarketOS edge with Phosh - my PinePhone with Arch Linux ARM and my Librem 5 running PureOS all show the same phenomenon.

IIRC, the beta was fine and fit perfectly - maybe this helps with finding the issue.

Nitpick, not important: For perfect adaptiveness, the Shortcuts window needs to be slightly more narrow: ![tangram-too-wide-3](https://user-images.githubusercontent.com/32742559/218252185-a0118b4e-b081-497a-92e4-72ac447b976d.png)

**Comment by sonnyp** [comment] 2023-02-11 10:15
Hey Peter :wave: 

The issue is already solved in `main` and will be included in the next release.

Regarding the screenshot window, I'm afraid it's a problem for another time; we don't have a pattern/primitive for that yet.

**Comment by 1peter10** [comment] 2023-02-11 12:52
Great :)

**Closed** 2023-04-30 07:45 UTC
