### ISSUE TITLE
Feature Request: Dynamic Hiding of the webapp selector

### ISSUE THREAD

**Issue by vega-d** [sonnyp/Tangram#158] opened 2021-11-14 10:03 UTC
It would be great if when app is resized to be small it hid the bar into a burger menu. Would also improve usability on mobile.

![image](https://user-images.githubusercontent.com/35414314/141676437-e0071c6a-f4d5-4712-8ae7-c101ff6c28e6.png)

**Comment by sonnyp** [comment] 2021-11-14 13:34
Duplicate of https://github.com/sonnyp/Tangram/issues/87

**Closed by sonnyp** 2021-11-14 13:34 UTC
