### ISSUE TITLE
Application not launching — cannot open display:

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#96] opened 2020-09-12 04:53 UTC
Tangram version: Flatpak 1.3.0
Linux distribution: Pop!_OS 20.04
Flatpak version: 1.6.5
Desktop environment: GNOME Shell 3.36 X11

Since updating to 1.3.0 with Flatpak, the application no longer launches

```
# flatpak run re.sonny.Tangram
Gjs-Message: 22:50:30.596: JS LOG: gjs 1.64.4
Gjs-Message: 22:50:30.596: JS LOG: WebKitGTK 2.28.4
Gjs-Message: 22:50:30.596: JS LOG: env: flatpak
Gjs-Message: 22:50:30.597: JS LOG: data_dir: /home/mmstick/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 22:50:30.597: JS LOG: cache_dir: /home/mmstick/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 22:50:30.597: JS LOG: config_dir: /home/mmstick/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 22:50:30.597: JS LOG: applications_dir: /home/mmstick/.local/share/applications
Gjs-Message: 22:50:30.597: JS LOG: keyfile_settings_path: 
Gjs-Message: 22:50:30.600: JS LOG: bin: re.sonny.Tangram
Gjs-Message: 22:50:30.600: JS LOG: default_icon: re.sonny.Tangram
Gjs-Message: 22:50:30.600: JS LOG: flag TANGRAM_ENABLE_CUSTOM_APPLICATIONS false
Gjs-Message: 22:50:30.600: JS LOG: flag TANGRAM_ENABLE_CUSTOM_ICONS false
Gjs-Message: 22:50:30.607: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 22:50:30.607: JS LOG: _: /usr/bin/dbus-update-activation-environment
Gjs-Message: 22:50:30.607: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 22:50:30.607: JS LOG: pkg.datadir: /app/share
Gjs-Message: 22:50:30.607: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 22:50:30.607: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 22:50:30.607: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 22:50:30.607: JS LOG: pkg.pkglibdir: /app/lib/Tangram
Gjs-Message: 22:50:30.607: JS LOG: pkg.version: 1.3.0
Gjs-Message: 22:50:30.607: JS LOG: pkg.prefix: /app
Gjs-Message: 22:50:30.607: JS LOG: pkg.pkgdatadir: /app/share/Tangram
Gjs-Message: 22:50:30.608: JS LOG: argv /app/bin/re.sonny.Tangram
Gtk-Message: 22:50:30.608: Failed to load module "appmenu-gtk-module"
Unable to init server: Could not connect: Connection refused

(re.sonny.Tangram:2): Gtk-WARNING **: 22:50:30.615: cannot open display:                                                                                              
# 
```

**Comment by sonnyp** [comment] 2020-09-12 08:33
I can't reproduce the issue on GNOME Shell 3.36 X11

Most likely the change that is causing this is https://github.com/flathub/re.sonny.Tangram/commit/00612a94f3acaa62fe6bbba2f29aa71d5e9cbe5c

Can you share the output of 

`flatpak run --verbose re.sonny.Tangram` ?

**Comment by mmstick** [comment] 2020-09-12 15:32
```
# flatpak --verbose run re.sonny.Tangram
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Cleaning up unused container id 1227433200
F: Allocated instance id 2069941161
F: Add defaults in dir /re/sonny/Tangram/
F: Add locks in dir /re/sonny/Tangram/
F: Disallowing ipc access
F: Allowing dri access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/mmstick/.config/pulse/client.conf': Error opening file /home/mmstick/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 30 xdg-dbus-proxy --args=32'
F: Running 'bwrap --args 30 re.sonny.Tangram'
Gjs-Message: 09:31:40.350: JS LOG: gjs 1.64.4
Gjs-Message: 09:31:40.350: JS LOG: WebKitGTK 2.28.4
Gjs-Message: 09:31:40.350: JS LOG: env: flatpak
Gjs-Message: 09:31:40.350: JS LOG: data_dir: /home/mmstick/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 09:31:40.350: JS LOG: cache_dir: /home/mmstick/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 09:31:40.350: JS LOG: config_dir: /home/mmstick/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 09:31:40.351: JS LOG: applications_dir: /home/mmstick/.local/share/applications
Gjs-Message: 09:31:40.351: JS LOG: keyfile_settings_path:
Gjs-Message: 09:31:40.354: JS LOG: bin: re.sonny.Tangram
Gjs-Message: 09:31:40.354: JS LOG: default_icon: re.sonny.Tangram
Gjs-Message: 09:31:40.354: JS LOG: flag TANGRAM_ENABLE_CUSTOM_APPLICATIONS false
Gjs-Message: 09:31:40.354: JS LOG: flag TANGRAM_ENABLE_CUSTOM_ICONS false
Gjs-Message: 09:31:40.361: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 09:31:40.361: JS LOG: _: /usr/bin/dbus-update-activation-environment
Gjs-Message: 09:31:40.361: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 09:31:40.361: JS LOG: pkg.datadir: /app/share
Gjs-Message: 09:31:40.361: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 09:31:40.361: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 09:31:40.361: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 09:31:40.361: JS LOG: pkg.pkglibdir: /app/lib/Tangram
Gjs-Message: 09:31:40.361: JS LOG: pkg.version: 1.3.0
Gjs-Message: 09:31:40.361: JS LOG: pkg.prefix: /app
Gjs-Message: 09:31:40.361: JS LOG: pkg.pkgdatadir: /app/share/Tangram
Gjs-Message: 09:31:40.362: JS LOG: argv /app/bin/re.sonny.Tangram
Gtk-Message: 09:31:40.362: Failed to load module "appmenu-gtk-module"
Unable to init server: Could not connect: Connection refused

(re.sonny.Tangram:2): Gtk-WARNING **: 09:31:40.368: cannot open display:
```

**Comment by sonnyp** [comment] 2020-09-12 15:50
You're not getting 

```
Allowing x11 access
```

no idea why sorry. You can use `flatpak-override` or https://github.com/tchx84/Flatseal as a workaround to explicitly allow x11

**Comment by mmstick** [comment] 2020-09-12 18:10
It only works when running

```
flatpak run --nosocket=fallback-x11 --socket=x11 re.sonny.Tangram
```

So `fallback-x11` breaks support for X11 with Flatpak 1.6.5 in Ubuntu 20.04

**Comment by sonnyp** [comment] 2020-09-27 14:21
flathub's flatpak fixed in https://github.com/flathub/re.sonny.Tangram/pull/9

**Closed by sonnyp** 2020-09-27 14:21 UTC

**Comment by mediapinta** [comment] 2023-08-07 18:43
I have a similar problem...

Tangram 3.0
Flatpak 1.14.4-1ubuntu1
Ubuntu 23.04
X11
GNOME Shell 44.3

`$ flatpak run --verbose re.sonny.Tangram
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/ifrit/.local/share/flatpak
F: Opening user flatpak installation at path /home/ifrit/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/re.sonny.Tangram/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/ifrit/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/584d7c3e03c7315975c6711d6503622c0b39c109b6faa89254a87d24cf918c6e/files/lib32 does not exist
F: Cleaning up unused container id 999218682
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3625905538
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3889736021
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 1622799297
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3001560576
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 1527853880
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3966962379
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3196684176
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 50840437
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 2386398304
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 3463299343
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Cleaning up unused container id 1597431811
F: Cleaning up per-app-ID state for re.sonny.Tangram
F: Allocated instance id 1677875569
F: Add defaults in dir /re/sonny/Tangram/
F: Add locks in dir /re/sonny/Tangram/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/ifrit/.config/pulse/client.conf': Erro ao abrir o ficheiro /home/ifrit/.config/pulse/client.conf: Ficheiro ou pasta inexistente
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 re.sonny.Tangram'
Gjs-Message: 20:27:24.664: JS LOG: env: flatpak
Gjs-Message: 20:27:24.665: JS LOG: data_dir: /home/ifrit/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 20:27:24.665: JS LOG: cache_dir: /home/ifrit/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 20:27:24.665: JS LOG: config_dir: /home/ifrit/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 20:27:24.665: JS LOG: applications_dir: /home/ifrit/.local/share/applications
Gjs-Message: 20:27:24.665: JS LOG: keyfile_settings_path:`

I changed from Wayland to X11 because one program didn't work well and the instructions were easier, and now Tangram isn't working *cries*

Thank you.

Greetings,
ifrit

P.S.: I don't know why the code doesn't keep the line breaks. Sorry.
